SYSTARG=Linux
<../../mkconfig
SYSTARG=Linux

#Configurable parameters

CONF=emu			#default configuration
CONFLIST=emu emu-t
CLEANCONFLIST=

INSTALLDIR=$ROOT/$SYSTARG/$OBJTYPE/bin	#path of directory where kernel is installed

#end configurable parameters

X11LIBS= -lX11 -lXext	# can remove or override using env section in config files

<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE	#set vars based on target system

<| $SHELLNAME ../port/mkdevlist $CONF	#sets $IP, $DEVS, $PORT, $LIBS
<mkfile-$OBJTYPE	# sets $ARCHFILES

OBJ=\
	asm-$OBJTYPE.$O\
	$ARCHFILES\
	os.$O\
	kproc-pthreads.$O\
	segflush-$OBJTYPE.$O\
	$CONF.root.$O\
	lock.$O\
	$DEVS\
	$PORT\

LIBNAMES=${LIBS:%=lib%.a}
#libs=${LIBS:%=$ROOT/$OBJDIR/lib/lib%.a}

HFILES=\

CFLAGS='-DROOT="'$ROOT'"' -DEMU -I. -I../port -I$ROOT/$SYSTARG/$OBJTYPE/include -I$ROOT/include -I$ROOT/libinterp $CTHREADFLAGS $CFLAGS $EMUOPTIONS
SYSLIBS= $X11LIBS -lm -lpthread
KERNDATE=`{$NDATE}

default:V:	$O.$CONF

$O.$CONF:	$OBJ $CONF.c $CONF.root.h $LIBNAMES
	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
	$LD $LDFLAGS -o $target $OBJ $CONF.$O $LIBFILES $SYSLIBS

install:V: $O.$CONF
	cp $O.$CONF $INSTALLDIR/$CONF

<../port/portmkfile

devfs.$O:	../port/devfs-posix.c
devds.$O:	../port/devds.c

# Regression tests, on the headless configuration (no X server needed):
#	mk test
# builds emu-t and the tests in ../test, then runs ../test/run.sh in it; the exit
# status of mk is that of emu-t (0 when every test passed).
test:V:
	mk CONF=emu-t install
	(cd ../test; mk install)
	env -u DISPLAY $INSTALLDIR/emu-t -r$ROOT -c1 -g1024x768 /dis/sh.dis /dis/test/run.sh
