#include "lib9.h"
#include "isa.h"
#include "interp.h"

void	decgen(int);

/*
 * Force intermediate dereference of $o(o(reg)) modes to ensure intermediate
 * pointer is valid. This is required if you want secure memory.
 */
#define	SOFTMMU		0

void
main(void)
{
	int i;

	HOSTED_API(print)("/* Machine generated by decgen.c */\n\n");

	HOSTED_API(print)("#include \"lib9.h\"\n");
	HOSTED_API(print)("#include \"isa.h\"\n");
	HOSTED_API(print)("#include \"interp.h\"\n\n");

	HOSTED_API(print)("#define DIND(reg, xxx) (uchar*)((*(ulong*)(R.reg+R.PC->xxx.i.f))+R.PC->xxx.i.s)\n");

	for(i = 0; i < 256; i++)
		decgen(i);

	HOSTED_API(print)("\nvoid	(*dec[])(void) =\n{\n");
	for(i = 0; i < 256; i++)
		HOSTED_API(print)("\tD%.2uX%c\n", i, i != 255 ? ',' : ' ');
	HOSTED_API(print)("};\n");
}

void
decgen(int addr)
{
	int nodst;

	HOSTED_API(print)("static void\nD%.2uX(void)\n{\n", addr);

	switch(USRC(addr)) {
	case AMP:
		HOSTED_API(print)("\tR.s = R.MP+R.PC->s.ind;\n");
		break;
	case AFP:
		HOSTED_API(print)("\tR.s = R.FP+R.PC->s.ind;\n");
		break;
	case AIMM:
		HOSTED_API(print)("\tR.s = (uchar*)&R.PC->s.imm;\n");
		break;
	case AMP|AIND:
		if(SOFTMMU) {
			HOSTED_API(print)("R.s = R.MP+R.PC->s.i.f\n");
			HOSTED_API(print)("R.s = *(WORD**)R.s\n");
			HOSTED_API(print)("R.s = (uchar*)R.s + R.PC->s.i.s\n");
		}
		else
			HOSTED_API(print)("\tR.s = DIND(MP, s);\n");
		break;
	case AFP|AIND:
		if(SOFTMMU) {
			HOSTED_API(print)("R.s = R.FP+R.PC->s.i.f\n");
			HOSTED_API(print)("R.s = *(WORD**)R.s\n");
			HOSTED_API(print)("R.s = (uchar*)R.s + R.PC->s.i.s\n");
		}
		else
			HOSTED_API(print)("\tR.s = DIND(FP, s);\n");
		break;
	}
	nodst = 0;
	switch(UDST(addr)) {
	default:
		nodst = 1;
		break;
	case AMP:
		HOSTED_API(print)("\tR.d = R.MP+R.PC->d.ind;\n");
		break;
	case AFP:
		HOSTED_API(print)("\tR.d = R.FP+R.PC->d.ind;\n");
		break;
	case AIMM:
		HOSTED_API(print)("\tR.d = (uchar*)&R.PC->d.imm;\n");
		break;
	case AMP|AIND:
		if(SOFTMMU) {
			HOSTED_API(print)("R.d = R.MP+R.PC->d.i.f\n");
			HOSTED_API(print)("R.d = *(WORD**)R.d\n");
			HOSTED_API(print)("R.d = (uchar*)R.d + R.PC->d.i.s\n");
		}
		else
			HOSTED_API(print)("\tR.d = DIND(MP, d);\n");
		break;
	case AFP|AIND:
		if(SOFTMMU) {
			HOSTED_API(print)("R.d = R.FP+R.PC->d.i.f\n");
			HOSTED_API(print)("R.d = *(WORD**)R.d\n");
			HOSTED_API(print)("R.d = (uchar*)R.d + R.PC->d.i.s\n");
		}
		else
			HOSTED_API(print)("\tR.d = DIND(FP, d);\n");
		break;
	}

	if(nodst == 0)
	switch(addr&ARM) {
	case AXNON:
		HOSTED_API(print)("\tR.m = R.d;\n");
		break;
	case AXIMM:
		HOSTED_API(print)("\tR.t = (short)R.PC->reg;\n");
		HOSTED_API(print)("\tR.m = &R.t;\n");
		break;
	case AXINF:
		HOSTED_API(print)("\tR.m = R.FP+R.PC->reg;\n");
		break;
	case AXINM:
		HOSTED_API(print)("\tR.m = R.MP+R.PC->reg;\n");
		break;
	}
	HOSTED_API(print)("}\n");
}
