<../mkconfig

LIB=libkern.a

OFILES=\
	callback.$O\
	heapprof.$O\
	memprof.$O\
	avlfree.$O\
	pool.$O\

HFILES=\
	$ROOT/include/inferno/callback.h\
	$ROOT/include/inferno/memprof.h\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE

