<../mkconfig

all:V:	all-$HOSTMODEL
install:V:	install-$HOSTMODEL
safeinstall:V:	safeinstall-$HOSTMODEL
clean:V:	clean-$HOSTMODEL
nuke:V:	nuke-$HOSTMODEL

&-Posix:QV:
	echo "(cd $SYSTARG; mk $MKFLAGS $stem)"
	(cd $SYSTARG; mk $MKFLAGS $stem) || exit 1
