<../mkconfig

LIB=libbio.a
OFILES=\
	bfildes.$O\
	bflush.$O\
	bgetrune.$O\
	bgetc.$O\
	binit.$O\
	boffset.$O\
	bprint.$O\
	bputrune.$O\
	bputc.$O\
	brdline.$O\
	bread.$O\
	bseek.$O\
	bvprint.$O\
	bwrite.$O\

HFILES=	$ROOT/include/bio.h

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
