<../mkconfig

#
#	Utils we build everywhere, because the Plan 9 versions don't yet
#	contain our changes (or they don't exist on Plan 9).
#	Fairly soon the Plan 9 compilers will be updated to match.
#
ALWAYS=\
	libregexp\
	iyacc\
	cc\
	ftl\
	data2c\
	data2s\
	idea\
	c2l\

#
#	Utils we build on Posix and Nt, which already exist on Plan 9.
#
NOTPLAN9=\
	mk\
	md5sum\
	mkext\
	ndate\

#
# Thumb-1
#
OBSOLETE=\

all:QV:		all-$TARGMODEL
clean:QV:	clean-$TARGMODEL
install:QV:	install-$TARGMODEL
installall:QV:	installall-$TARGMODEL
nuke:QV:	nuke-$TARGMODEL

%-Posix:QV:
	for j in  $ALWAYS $NOTPLAN9
	do
		test -d $j || continue
		echo "(cd $j; mk $MKFLAGS $stem)"
		(cd $j; mk $MKFLAGS $stem) || exit 1
	done
